### PR TITLE
WIP: Upgrade silverstripe-sharethis to SS4

### PR DESCRIPTION
**Pull request by MasseyIsaako**

### CODE REVIEW

**Comment by sunnysideup** [comment]
Awesome! THANK YOU

**Comment by MasseyIsaako** [comment]
Hi @sunnysideup,
Seems like you merged in my pull request a little prematurely :) I marked it WIP for Work in Progress, so you may need to revert that as others who may be using this codebase will likely experience a lot of bugs. 

Apologies for the confusion :)

**Comment by sunnysideup** [comment]
Hi,

No confusion... I just wanted to acknowledge your work. THANK YOU. I have made a tag and a branch for 3.0 - now we are going to 4.0.

Did you know we have written a tool for upgrading to SS4? https://github.com/sunnysideup/silverstripe-upgrade_to_silverstripe_4

One thing.  Can you change vendor to Sunnysideup rather Than SunnySideUp?

I am happy to give you access to the module itself if that would help.

Cheers

Nicolaas

**Comment by MasseyIsaako** [comment]
No worries, I can make that namespacing change available in my next pull request :)

I'd prefer that you keep access to the module, just to ensure that what I upgrade isn't breaking anything and so we maintain transparency about what's going into your master branch.

Thanks!

**Comment by sunnysideup** [comment]
Sounds great.  Master is there to be broken. Once we have a solid SS4 code base, we will tag it.

Thanks again for you interest and support.

**Pull request merged**
